### ISSUE TITLE
Column of type boolean

### ISSUE THREAD

**Issue by kjetilmjos** [wbh1/grafana-sqlite-to-postgres#5]
Tried your code for migration from sqlite to postgres. Got the following error message 
`FATAL[2019-11-01T10:29:03+01:00] ❌ pq: column "is_disabled" is of type boolean but expression is of type integer INSERT INTO "user" VALUES(1,0,'admin','admin@localhost','','72ed5e71f200bbead950d19d5bd2994815611e18572cd41651745d121ce9af192acdcdad8104247871fab2b492a6c889ee92','fGPVL71GjF','zXNp0r9TCh','',1,1,0,'','2018-09-14 08:25:51','2018-09-14 08:25:51',0,'2019-10-31 21:13:49',0); - failed to import dump file to Postgres.`

Any idea whats going on?

**Comment by kjetilmjos** [comment]
Found the issue. The latest binary files in the repo are not built after last commit. Downloaded the source and built it my self. Then everything worked :)

**Comment by wbh1** [comment]
Sorry for the delay in responding, I was on my honeymoon 😁 I'm going to work on setting up automatic builds to prevent this in the future.

**Comment by kjetilmjos** [comment]
No worries ;) thanks for a great piece of software 👍

**Comment by wbh1** [comment]
This is fixed now. New binaries will auto-build and be attached to releases in the future 🎉

**Comment by krakazyabra** [comment]
Problem still exists in package release. 
Downloaded [release](https://github.com/wbh1/grafana-sqlite-to-postgres/releases/tag/v2.2.3)
created db
started grafana
wait for the migrations to finish
stopped grafana
```shell
❯ ./grafana-migrate_darwin_amd64-v2.2.3 grafana.db "postgres://grafana:<pass>@localhost:5432/grafana?sslmode=disable"
INFO[2023-05-26T11:59:24+02:00] 📁 SQLlite file: grafana.db
INFO[2023-05-26T11:59:24+02:00] 📁 Dump directory: /tmp
INFO[2023-05-26T11:59:24+02:00] ✅ sqlite3 command exists
INFO[2023-05-26T11:59:26+02:00] ✅ sqlite3 database dumped to /tmp/grafana.sql
INFO[2023-05-26T11:59:34+02:00] ✅ CREATE statements removed from dump file
INFO[2023-05-26T11:59:52+02:00] ✅ sqlite3 dump sanitized
INFO[2023-05-26T12:00:03+02:00] ✅ migration_log statements removed
INFO[2023-05-26T12:00:04+02:00] ✅ char keyword transformed
INFO[2023-05-26T12:00:06+02:00] ✅ hex-encoded data values wrapped for insertion
FATAL[2023-05-26T12:00:14+02:00] ❌ pq: column "is_revoked" is of type boolean but expression is of type integer INSERT INTO "api_key" VALUES(4,1,'admin','b4adea4a943fd06c187837f6e559fd44b19dfc51b3de23a0387a4ce53ee01389e8c425e2cc55489f18f540ec6d3252ffa0b1','Admin','2022-05-19 13:25:46','2022-05-19 13:25:46',NULL,NULL,NULL,0) - failed to import dump file to Postgres.
```

In the same time building from sources works:
Compiled app from sources (commit d7b0c69534a6b82bf16ead7483e36b04afe90363)
created db
started grafana
wait for the migrations to finish
stopped grafana
built app
```shell
❯ make build
go build -o dist/grafana-migrate_darwin_arm64-+refs/tags/v2.2.3-6-gd7b0c69 ./cmd/grafana-migrate
go: downloading github.com/sirupsen/logrus v1.9.0
go: downloading gopkg.in/alecthomas/kingpin.v2 v2.2.6
go: downloading github.com/lib/pq v1.10.7
go: downloading golang.org/x/sys v0.0.0-20221013171732-95e765b1cc43
go: downloading github.com/alecthomas/template v0.0.0-20190718012654-fb15b899a751
go: downloading github.com/alecthomas/units v0.0.0-20211218093645-b94a6e3cc137
```

run 
```shell
❯ ./grafana-migrate_darwin_amd64-v2.2.3 grafana.db "postgres://grafana:<pass>@localhost:5432/grafana?sslmode=disable"
INFO[2023-05-26T12:05:55+02:00] 📁 SQLlite file: grafana.db
INFO[2023-05-26T12:05:55+02:00] 📁 Dump directory: /tmp
INFO[2023-05-26T12:05:55+02:00] ✅ sqlite3 command exists
INFO[2023-05-26T12:05:56+02:00] ✅ sqlite3 database dumped to /tmp/grafana.sql
INFO[2023-05-26T12:05:58+02:00] ✅ CREATE statements removed from dump file
INFO[2023-05-26T12:06:10+02:00] ✅ sqlite3 dump sanitized
INFO[2023-05-26T12:06:16+02:00] ✅ migration_log statements removed
INFO[2023-05-26T12:06:17+02:00] ✅ char keyword transformed
INFO[2023-05-26T12:06:18+02:00] ✅ hex-encoded data values wrapped for insertion

INFO[2023-05-26T12:15:29+02:00] ✅ Imported dump file to Postgres
INFO[2023-05-26T12:15:29+02:00] 🎉 All done!
```
